#!/usr/bin/env python2.7

#File: lebailly/BME205/main
#Author: Chris LeBailly

"""
main
"""

from __future__ import division, print_function
import sys, argparse, collections, re
import FastaFastq

def main(args):
	args = FastaFastq.parse_arguments()

	for name, seq, comment, qual in FastaFastq.read_fastq(args.input, args):
		if(len(qual) < 500):
			print(qual)



	#quality = open('tiny.qual', 'r')
	#fasta = open('tiny.fasta','r')

	#for name, seq, qual in read_fasta_with_quality(fasta,quality):
	#	print('Name:', name, '\n Sequence:', seq, '\n Quality:', qual, '\n\n')

	#fasta.close()
	#quality.close()

if __name__ == "__main__" :
    sys.exit(main(sys.argv))